#!/bin/sh
### BEGIN INIT INFO
# Provides:          janosh-root
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the root and lounge janosh instances
# Description:
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/lounge/bin/janosh"
LOG_ROOT="/var/log/janosh-root.log"
OPTS="-dvpm"
DESC="janosh"
NAME="janosh"

test -x $DAEMON || exit 1

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
      log_daemon_msg "Starting $DAEMON root"
      start-stop-daemon --start --background --pidfile /var/run/janosh-root.pid --make-pidfile --user root --chuid root --startas /bin/bash -- -c "export HOME=/root/; export USER=root; exec $DAEMON $OPTS &> /var/log/janosh-root.log"
      export HOME=/root/;
      export USER=root;
      while ! /lounge/bin/janosh dump; do
        echo "Waiting for connection"
        sleep 1
      done

      log_end_msg $?
    ;;

  stop)
    log_daemon_msg "Stopping $DAEMON root"
    start-stop-daemon --stop --pidfile /var/run/janosh-root.pid --retry 10
    log_end_msg $?
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
