#!/bin/sh
### BEGIN INIT INFO
# Provides: screeninvader-root
# Required-Start: janosh
# Required-Stop: janosh
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the screeinvader root components
# Description:
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
COMPONENTS="network display system"

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
  for comp in $COMPONENTS; do 
      log_daemon_msg "Starting $comp"
      start-stop-daemon --start --background --pidfile /var/run/$comp.lua.pid --make-pidfile --user root --chuid root -d /root/lua/ --startas /bin/bash -- -l -c "export HOME=/root; export USER=root;cd /root/lua; exec /lounge/bin/janosh -vf /root/lua/$comp.lua &> /var/log/$comp.log"
      log_end_msg $?
  done
    ;;

  stop)

  for comp in $COMPONENTS; do
    log_daemon_msg "Stopping $comp"
    start-stop-daemon -s TERM --stop --oknodo --pidfile /var/run/$comp.lua.pid --retry 10
    log_end_msg $?
  done
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
