#!/bin/bash

FUNCTION="$1"

function makeHostname() {
  echo "$1" > "/etc/hostname"
}

function makeNetworkDhcp() {

  cat > /etc/network/interfaces <<EODHCPCONF
auto lo $1
iface lo inet loopback
allow-hotplug $1
iface $1 inet dhcp
EODHCPCONF
}

function makeNetworkMan() {
  cat > /etc/network/interfaces <<EONETCONF
auto lo $1
iface lo inet loopback
allow-hotplug $1
iface $1 inet static
address $2
netmask $3
gateway $4
EONETCONF
}

function makeDns() {
  cat > /etc/resolv.conf <<EORESOLVCONF
domain local
search local
nameserver $1
EORESOLVCONF
}

function addWifi() {

enc="$1"

cat >> /etc/network/interfaces <<EOWIFICONF
wpa-ssid $2
wpa-ap-scan 1
wpa-key-mgmt $enc
EOWIFICONF

if [ "$enc" != "NONE" ]; then
  cat >> /etc/network/interfaces <<EOPHRASE
wpa-psk $3
EOPHRASE
fi
}

function readWirelessNics() {
  cat /proc/net/wireless | grep -Po '^ \K([A-Za-z0-9]*)(?=:)'
}

function readWiredNics() {
  cat /proc/net/dev | grep -Po '^\s*\K(e[A-Za-z0-9]*)(?=:)'
}

function readHostname() {
  cat /etc/hostname
}

function reload() {
  i=0

  janosh set /network/hostname "$(readHostname)"

  readWiredNics | while read c; do
    janosh set "/network/connection/wired/choices/#$i" "$c"
    i=$[$i+1]
  done

  readWirelessNics | while read c; do
    janosh set "/network/connection/wireless/choices/#$i" "$c"
    i=$[$i+1]
  done

  restart
  killall osd
  sudo -u lounge /lounge/bin/showip &
}

function restart() {
  readWirelessNics | xargs -Ibla -n1 ifconfig bla down
  readWiredNics | xargs -Ibla -n1 ifconfig bla down
  /etc/init.d/networking stop
  /etc/init.d/networking start
  ifup "${DATA[/network/connection/interface]}"
}

function apply() {
  makeNetwork
  makeDns
  makeHostname
  restart
}

if [ "$(type -t "$FUNCTION")" == "function" ]; then
  $FUNCTION
else
  echo "Unknown command: $FUNCTION" 1>&2
  exit 1
fi


