#!/bin/bash

cat <<EOSYSLINUX
DEFAULT screeninvader
LABEL screeninvader
  SAY Booting ScreenInvader
	KERNEL /vmlinuz
	APPEND quiet splash ro init=/bin/systemd root=UUID=$1 initrd=/initrd.img
EOSYSLINUX

