#!/bin/bash

export DISPLAY=:0
export HOME=/lounge
export USER=lounge
export PATH="$HOME/bin:/lounge/www/cgi-bin/:$PATH"
export LOGDIR="/var/log/lounge"

echo "Content-type: $1"
echo ""
cd $HOME/www/cgi-bin/

