#!/bin/bash

. ./initcgi "text/html"

URL="$QUERY_STRING"

cat <<EOHTML
<html>
<head>
<style>
html { 
  background-image: url($URL);
  background-color: black;
  background-repeat: no-repeat;
  background-position: center center;
  -webkit-background-size: contain;
  -moz-background-size: contain;
  -o-background-size: contain;
  background-size: contain;
}
</style>
</head>
<body>
</body>
</html>
EOHTML
