#!/bin/bash
. ./initcgi "text/html"
{
set -x
  read
  read line
  filename="$(echo $line | grep -iPo 'filename="\K(.*)?(?=")')"
  read line
  contentType="$(echo $line | grep -iPo 'Content-Type: \K(.*)?(?=)')"
  read 
  if echo "$contentType" | grep -E "(video|matroska|audio|octet-stream)"; then
    tmp="$(mktemp -u)"
    mkfifo "$tmp"
    janosh publish playerLoadFile "$tmp"
    sleep 1
    dd if=/dev/stdin of="$tmp"
  elif echo "$contentType" | fgrep "image"; then
    mkdir -p /lounge/www/tmp
    tmp="/lounge/www$(mktemp).jpg"    

    dd if=/dev/stdin > "$tmp"
    janosh publish showUrl "http://localhost/tmp/$(basename $tmp)"
  fi
} &> /tmp/upload
cat /lounge/www/close.html

